apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment-gitlab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app-gitlab
  template:
    metadata:
      labels:
        app: node-app-gitlab
    spec:
      containers:
        - name: node-app-gitlab
          image: registry.gitlab.com/prathmesh.arcade/node-js-appication:112bfa
          ports:
            - containerPort: 3000
          env:
            - name: ENV
              value: "production"
